@startuml State Machine
class ReturnToHomeAndRest{
    +Enter()
    +Execute()
    +Exit()
    -家に行き休憩する
}
class EnterForestAndPickupItem{
    +Enter()
    +Execute()
    +Exit()
    -森に行き素材を集める
}
class GoAteilerAndSynthesis{
    
    +Enter()
    +Execute()
    +Exit()
    -アトリエで調合する
    
}
ReturnToHomeAndRest->EnterForestAndPickupItem: 素材が足りていなかったら
ReturnToHomeAndRest->GoAteilerAndSynthesis: 素材が足りていたら
EnterForestAndPickupItem-->GoAteilerAndSynthesis: ポケットがいっぱいになったら
EnterForestAndPickupItem->ReturnToHomeAndRest: 疲労度が上がったら
GoAteilerAndSynthesis-->EnterForestAndPickupItem: 素材が無くなったら
@enduml
